language: node_js

matrix:
  include:
    - node_js: '8.9'
    - node_js: '10.6'

sudo: false

install:
  - travis_retry npm install

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
